### ISSUE TITLE
CliNews não funcionou muito bem no WSL

### ISSUE THREAD

**Issue by Jbnado** [eduardo-moro/CliNews#3]
Olá, eu tentei baixar no WSL e não funcionou muito bem:
![image](https://user-images.githubusercontent.com/73846881/173568658-4de1da90-db05-4d0d-9304-fe558b9d10df.png)
Vocês pensam que é por causa do WSL? Ou faltou algo que eu precisava instalar?

**Comment by eduardo-moro** [comment]
Opa, tudo bem? 
😅 eu fiz uma coisa muito feia na verdade, juro que não vou repetir

Estou trabalhando na correção da forma como as tabelas estão sendo separadas, já eram umas 3 da manhã quando parei de trabalhar e fui dar uma atenção pra o projeto, subi na manhã de ontem e ainda tava com problemas, vou tentar tirar um tempinho hoje pra corrigir, mas está assim mesmo infelizmente

**Comment by Jbnado** [comment]
Ah entendi, fica tranquilo haha vou aguardar sempre pra isso ficar pronto <3, já está lindo.

**Comment by eduardo-moro** [comment]
Pode deixar que eu te dou um @ aqui quando corrigir!

**Comment by eduardo-moro** [comment]
@Jbnado dei uma atualizada durante o dia, só falta corrigir os cliques pra poder selecionar as noticias, mas a função que troca a notícia já está lá, junto com a notícia sendo mostrada com markdown sendo processado :)
